### PR TITLE
EN-16375 Retry another secondary if the chosen secondary contains the…

### PR DESCRIPTION
**Pull request by chitang**
… primary table but not a joined table.

### CODE REVIEW

**Comment by znep** [comment]
Would it make sense to instead do all the logic of figuring this out inside the secondary instance selector?  

We agreed we want to move towards a world where we get all schema from the secondaries (ie. eventually query coordinator will get the resource name instead of the internal name), so we need to get the resource name to in the data the secondary instance selector stores anyway.  Once we have that, the SecondaryInstanceSelector already knows which secondaries have all the datasets needed so we don't have to go back and forth making requests to secondaries until we figure it out.

**Comment by aerust** [comment]
Is there a way this could not be a retry?

**Comment by chitang** [comment]
I thought about that and don't have a strong preference on either.  I choose this because it requires much less (re)work.

**Comment by chitang** [comment]
I think this is as least a good option for now.

**Comment by aerust** [comment]
Okay, approving this with the agreement Chi is going to walk me through how to do the refactor so we can do this with the SecondaryInstanceSelector soon. 

:ship: :sheep:

**Comment by chitang** [comment]
Yeah, there is an intermediary route where you duplicate soql parsing to figure out what you need and feed the info to SecondaryInstanceSelector.  And then there is a more invasive refactoring where we move soql parsing higher up.  I think we should attempt the latter.

**Pull request merged**
