### PR TITLE
EN-55189: Bump soql ref for more aggressive soql chain merging  1. Allow merging with distinct where a.distinctiveness is indistinct and b.distinctiveness is not partial distinct. 2. Allow merging within join analysis

### PR DESCRIPTION
**Pull request by chitang**
…stinct and b.distinctiveness is not partial distinct.

### CODE REVIEW

**Comment by catstavi** [comment]
This commit message is awesome, thank you for breaking it out.
Going to be real that I don't understand this bit:
> Allow merging with distinct where a.distinctiveness is indistinct and b.distinctiveness is not partial distinct

do you have an example query or test that could help me figure it out?

**Comment by chitang** [comment]
There was a test in soql-reference.  This is just version bump here.

**Comment by chitang** [comment]
The original distinct merge didn't come with a test in soql-reference.  But I already made that up in the last PR you reviewed in soql-ref.

**Comment by chitang** [comment]
These are the tests you are asking for.  They live in soql-reference

+  test("indistinct, distinct is merged") {
+    val analysis1 = analyzer.analyzeFullQueryBinary("SELECT name_first, name_last |> SELECT distinct name_first")
+    val analysis2 = analyzer.analyzeFullQueryBinary("SELECT distinct name_first")
+    val merged = SoQLAnalysis.merge(TestFunctions.And.monomorphic.get, analysis1)
+    merged must equal (analysis2)
+  }
+
+  test("distinct, indistinct should be mergeable but the merger does not support this yet") {
+    val analysis = analyzer.analyzeFullQueryBinary("SELECT distinct name_first |> SELECT name_first")
+    val notMerged = SoQLAnalysis.merge(TestFunctions.And.monomorphic.get, analysis)
+    notMerged must equal (analysis)
+  }
+
+  test("distinct on is not mergeable") {
+    val analysis = analyzer.analyzeFullQueryBinary("SELECT name_first, name_last |> SELECT distinct on(name_first) name_first, name_last")
+    val notMerged = SoQLAnalysis.merge(TestFunctions.And.monomorphic.get, analysis)
+    notMerged must equal (analysis)
+  }

**Review by catstavi — APPROVED** [review]
thanks, having the soql examples is really helpful for me!

**Pull request merged**
